name: Build and Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    # 每天凌晨1:00运行
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 安装依赖项
        run: |
          npm install -g javascript-obfuscator
      - name: 下载 BPB worker.js
        run: |
          wget -O _worker.js https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/download/v3.3.9/worker.js
