name: Build BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    # 每天凌晨1:00运行 (UTC时间)
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载并重命名 BPB worker.js
        run: |
          wget -O _worker.js https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/download/v3.3.9/worker.js

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: 更新最新的 BPB Worker'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
